useEffect reference
reactjs/pl.react.dev pull request #431
Opened 2023-10-06 19:37 UTC by dawidowski

2023-10-07 11:19 UTC, jakubdrozdek requested changes

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Niektóre komponenty, gdy są wyświetlane na stronie, muszą pozostać połączone z siecią, pewnym interfejsem przeglądarki lub zewnętrzną biblioteką. Systemy te nie są kontrolowane przez Reacta, dlatego
Za dużo wtrąceń, przez co zdanie jest mocno poszatkowane i ciężko je zrozumieć.

```suggestion
Niektóre komponenty muszą pozostać połączone z siecią, pewnym interfejsem przeglądarki lub zewnętrzną biblioteką podczas wyświetlania ich na ekranie. Systemy te nie są kontrolowane przez Reacta, dlatego nazywane są *zewnętrznymi.*
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Aby użyć `useEffect`, musisz przekazać dwie argumenty:
```suggestion
Aby użyć `useEffect`, musisz przekazać dwa argumenty:
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +1. *Funkcję konfiguracyjną* z <CodeStep step={1}>kodem konfiguracyjnym</CodeStep>, który łączy się z tym systemem.
```suggestion
1. *Funkcję konfiguracyjną* z <CodeStep step={1}>kodem konfigurującym</CodeStep>, który łączy się z tym systemem.
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +2. <CodeStep step={3}>Tablicę zależności</CodeStep>, zawierającą każdą wartość używaną wewnątrz tych funkcji w twoim komponencie.
```suggestion
2. <CodeStep step={3}>Tablicę zależności</CodeStep>, zawierającą każdą wartość z twojego komponentu używaną wewnątrz tych funkcji.
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +1. Twój <CodeStep step={1}>kod konfiguracyjny</CodeStep> jest wykonywany, gdy twój komponent jest dodawany do strony *(montowany)*.
```suggestion
1. Twój <CodeStep step={1}>kod konfigurujący</CodeStep> jest wykonywany, gdy komponent jest dodawany do strony *(montowany)*.
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +   - Następnie jest wykonywany twój <CodeStep step={1}>kod konfiguracyjny</CodeStep> z nowymi właściwościami i stanem.
```suggestion
   - Następnie jest wykonywany twój <CodeStep step={1}>kod konfigurujący</CodeStep> z nowymi właściwościami i stanem.
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +3. Twój <CodeStep step={2}>kod czyszczący</CodeStep> jest wykonywany jeszcze raz po usunięciu *(odmontowaniu)* twojego komponentu ze strony.
```suggestion
3. Twój <CodeStep step={2}>kod czyszczący</CodeStep> jest wykonywany jeszcze raz po usunięciu *(odmontowaniu)* komponentu ze strony.
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +**Przyjrzyjmy się tej sekwencji z przykładu powyżej.**
```suggestion
**Przyjrzyjmy się tej sekwencji dla przykładu powyżej.**
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Kiedy komponent `ChatRoom` zostanie dodany do strony, połączy się z pokojem czatu przy użyciu początkowych `serverUrl` i `roomId`. Jeśli którakolwiek z zależności `serverUrl` lub `roomId` zmieni się
```suggestion
Kiedy komponent `ChatRoom` zostanie dodany do strony, połączy się z pokojem czatu przy użyciu początkowych `serverUrl` i `roomId`. Jeśli którakolwiek z zależności - `serverUrl` lub `roomId` - zmieni się w wyniku przerenderowania (np. jeśli użytkownik wybierze inny pokój czatu z rozwijanej listy), twój efekt *rozłączy się z poprzednim pokojem i połączy się z następnym.* Kiedy komponent `ChatRoom` zostanie usunięty ze strony, twój efekt rozłączy się ostatni raz.
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +**Aby [pomóc w wykrywaniu błędów,](/learn/synchronizing-with-effects#step-3-add-cleanup-if-needed) w trybie developerskim React wykonuje dodatkowo funkcję <CodeStep step={1}>setup</CodeStep> oraz <Co
```suggestion
**Aby [pomóc w wykrywaniu błędów,](/learn/synchronizing-with-effects#step-3-add-cleanup-if-needed) w trybie developerskim React wykonuje dodatkowo funkcję <CodeStep step={1}>konfigurującą</CodeStep> oraz <CodeStep step={2}>czyszczącą</CodeStep> przed właściwym, docelowym wywołaniem <CodeStep step={1}>konfigurującej</CodeStep>.** Jest to test obciążeniowy, który sprawdza, czy logika twojego efektu jest poprawnie zaimplementowana. Jeśli to spowoduje widoczne problemy, oznacza to, że brakuje pewnej logiki w funkcji czyszczącej. Funkcja ta powinna zatrzymać lub cofnąć wszystko, co zrobiła funkcja konfiguracyjna. Ogólnie rzecz biorąc, użytkownik nie powinien być w stanie rozróżnić między jednorazowym wywołaniem konfiguracji (jak na produkcji), a sekwencją *konfiguracja* → *czyszczenie* → *konfiguracja* (jak w trybie developerskim). [Zobacz najczęstsze rozwiązania.](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +**Postaraj się pisać każdy efekt jako niezależny proces** i **skup się na pojedynczym cyklu konfiguracji i czyszczenia w danym momencie.** Nie ma znaczenia, czy komponent jest montowany, aktualizowan
```suggestion
**Postaraj się pisać każdy efekt jako niezależny proces** i **skup się na pojedynczym cyklu konfigurowania i czyszczenia w danym momencie.** Nie ma znaczenia, czy komponent jest montowany, aktualizowany czy odmontowywany. Jeśli logika czyszczenia poprawnie odwzorowuje logikę konfigurowania, twój efekt jest odporny na uruchamianie konfigurowania i czyszczenia tak często, jak to konieczne.
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +W tym przykładzie komponent `ChatRoom` wykorzystuje efekt do utrzymania połączenia z systemem zewnętrznym zdefiniowanym w pliku `chat.js`. Naciśnij "Otwórz czat", aby pojawił się komponent `ChatRoom`
```suggestion
W tym przykładzie komponent `ChatRoom` wykorzystuje efekt do utrzymania połączenia z systemem zewnętrznym zdefiniowanym w pliku `chat.js`. Naciśnij "Otwórz czat", aby pojawił się komponent `ChatRoom`. Ta piaskownica działa w trybie developerskim, więc ma miejsce dodatkowy cykl łączenia i rozłączania, tak jak jest to [wyjaśnione tutaj](/learn/synchronizing-with-effects#step-3-add-cleanup-if-needed). Spróbuj zmieniać `roomId` i `serverUrl` za pomocą rozwijanej listy i pola tekstowego, a zobaczysz, jak efekt ponownie łączy się z czatem. Naciśnij "Zamknij czat", aby zobaczyć, jak efekt kończy połączenie po raz ostatni.
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +  const [roomId, setRoomId] = useState('ogólny');
```suggestion
  const [roomId, setRoomId] = useState('general');
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="ogólny">ogólny</option>
```suggestion
          <option value="general">ogólny</option>
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="podróże">podróże</option>
```suggestion
          <option value="travel">podróże</option>
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="muzyka">muzyka</option>
```suggestion
          <option value="music">muzyka</option>
```

2023-10-07 11:19 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +W tym przykładzie, systemem zewnętrznym jest biblioteka animacji w pliku `animation.js`. Udostępnia ona klasę javascriptową o nazwie `FadeInAnimation`, która przyjmuje jako argument węzeł DOM i udost
```suggestion
W tym przykładzie, systemem zewnętrznym jest biblioteka animacji w pliku `animation.js`. Udostępnia ona klasę javascriptową o nazwie `FadeInAnimation`, która przyjmuje jako argument węzeł DOM i udostępnia metody `start()` oraz `stop()` do sterowania animacją. Ten komponent [używa referencji (ang. *ref*)](/learn/manipulating-the-dom-with-refs), aby mieć dostęp do bazowego węzła DOM. Gdy komponent staje się widoczny, efekt odczytuje ten węzeł z referencji i automatycznie uruchamia dla niego animację.
```

2023-10-07 11:43 UTC, jakubdrozdek requested changes

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +W tym przykładzie, systemem zewnętrznym ponownie jest drzewo DOM w przeglądarce. Komponent `App` wyświetla długą listę, następnie komponent `Box`, a potem kolejną długą listę. Przewiń w dół tej listy
```suggestion
W tym przykładzie, systemem zewnętrznym ponownie jest drzewo DOM w przeglądarce. Komponent `App` wyświetla długą listę, następnie komponent `Box`, a potem kolejną długą listę. Przewiń w dół tej listy. Zauważ, że gdy komponent `Box` pojawia się cały w widocznym obszarze przeglądarki, kolor tła zmienia się na czarny. Aby to zaimplementować, komponent `Box` używa efektu do sterowania [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). To API przeglądarki powiadamia naszą funkcję, kiedy element DOM jest widoczny.
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +  const [roomId, setRoomId] = useState('ogólny');
```suggestion
  const [roomId, setRoomId] = useState('general');
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="ogólny">ogólny</option>
```suggestion
          <option value="general">ogólny</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="podróże">podróże</option>
```suggestion
          <option value="travel">podróże</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="muzyka">muzyka</option>
```suggestion
          <option value="music">muzyka</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Ten przykład jest identyczny jak [jeden z wcześniejszych przykładów,](#examples-connecting) ale logika została wyodrębniona do własnego hooka.
```suggestion
Ten przykład jest identyczny z [jednym z wcześniejszych,](#examples-connecting) ale logika została wyodrębniona do własnego hooka.
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Ten przykład jest identyczny jak [jeden z wcześniejszych przykładów,](#examples-connecting) ale logika została częściowo wyodrębniona do własnego hooka.
```suggestion
Ten przykład jest identyczny z [jednym z wcześniejszych,](#examples-connecting) ale logika została częściowo wyodrębniona do własnego hooka.
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Zwróć uwagę na zmienną `ignore`, która jest inicjowana jako `false` i ustawiana na `true` podczas czyszczenia. Zapewnia to, że [twój kod nie będzie podatny na tzw. "hazardy" (ang. *race conditions*):
```suggestion
Zwróć uwagę na zmienną `ignore`, która jest inicjowana jako `false` i ustawiana na `true` podczas czyszczenia. Zapewnia to, że [twój kod nie będzie podatny na tzw. "wyścigi" (ang. *race conditions*):](https://maxrozen.com/race-conditions-fetching-data-react-with-useeffect) odpowiedzi z sieci mogą przychodzić w innej kolejności, niż zostały wysłane żądania.
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Możesz to również przepisać, używając składni [`async` / `await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function), ale nadal musisz napisać funkcję czyszc
```suggestion
Możesz również przepisać ten kod używając składni [`async` / `await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function), ale nadal musisz napisać funkcję czyszczącą:
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +- **Nie jest to zbyt ergonomiczne.** Pisanie wywołania `fetch` w taki sposób, aby uniknąć błędów takich jak [hazardy](https://maxrozen.com/race-conditions-fetching-data-react-with-useeffect), wymaga
```suggestion
- **Nie jest to zbyt ergonomiczne.** Pisanie wywołania `fetch` w taki sposób, aby uniknąć błędów takich jak [wyścigi](https://maxrozen.com/race-conditions-fetching-data-react-with-useeffect), wymaga dość dużej ilości kodu.
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +- **W przeciwnym razie, rozważ użycie lub zbudowanie pamięci podręcznej po stronie klienta.** Popularne rozwiązania open source obejmują [React Query](https://react-query.tanstack.com/), [useSWR](htt
```suggestion
- **W przeciwnym razie, rozważ użycie lub zbudowanie pamięci podręcznej po stronie klienta.** Popularne rozwiązania open source obejmują [React Query](https://react-query.tanstack.com/), [useSWR](https://swr.vercel.app/) oraz [React Router 6.4+.](https://beta.reactrouter.com/en/main/start/overview) Możesz także zbudować swoje własne rozwiązanie, w którym byłyby użyte efekty, ale także zawarte byłyby: logika do unikania zduplikowanych zapytań, buforowania odpowiedzi i unikania kaskad żądań sieciowych (poprzez wstępne wczytywanie danych lub przeniesienie wymagań dot. danych do ścieżek).
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +**Aby usunąć zależność, musisz "udowodnić" linterowi, że to *nie musi być* zależność.** Na przykład, możesz przenieść `serverUrl` poza swój komponent i tym samym udowodnić, że nie jest wartość reakty
```suggestion
**Aby usunąć zależność, musisz "udowodnić" linterowi, że to *nie musi być* zależność.** Na przykład, możesz przenieść `serverUrl` poza swój komponent i tym samym udowodnić, że nie jest wartością reaktywną i nie zmieni się podczas ponownego renderowania:
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Jeśli określisz zależności, twój efekt zostanie uruchomiony **po początkowym renderowaniu _oraz_ po ponownym renderowaniu z zmienionymi zależnościami.**
```suggestion
Jeśli określisz zależności, twój efekt zostanie uruchomiony **po początkowym renderowaniu _oraz_ po ponownym renderowaniu ze zmienionymi zależnościami.**
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +}, [a, b]); // Zostanie uruchomiony ponownie, jeśli a lub b są różne
```suggestion
}, [a, b]); // Zostanie uruchomiony ponownie, jeśli a lub b ulegną zmianie
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +  const [roomId, setRoomId] = useState('ogólny');
```suggestion
  const [roomId, setRoomId] = useState('general');
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="ogólny">ogólny</option>
```suggestion
          <option value="general">ogólny</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="podróże">podróże</option>
```suggestion
          <option value="travel">podróże</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="muzyka">muzyka</option>
```suggestion
          <option value="music">muzyka</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +const roomId = 'muzyka';
```suggestion
const roomId = 'music';
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +  const [roomId, setRoomId] = useState('ogólny');
```suggestion
  const [roomId, setRoomId] = useState('general');
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="ogólny">ogólny</option>
```suggestion
          <option value="general">ogólny</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="podróże">podróże</option>
```suggestion
          <option value="travel">podróże</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="muzyka">muzyka</option>
```suggestion
          <option value="music">muzyka</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +  const [roomId, setRoomId] = useState('ogólny');
```suggestion
  const [roomId, setRoomId] = useState('general');
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="ogólny">ogólny</option>
```suggestion
          <option value="general">ogólny</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="podróże">podróże</option>
```suggestion
          <option value="travel">podróże</option>
```

2023-10-07 11:43 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +          <option value="muzyka">muzyka</option>
```suggestion
          <option value="music">muzyka</option>
```

2023-10-07 12:03 UTC, jakubdrozdek requested changes

2023-10-07 12:03 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Jeśli rzeczywiście synchronizujesz się z jakimś zewnętrznym systemem, zastanów się, dlaczego i pod jakim warunkiem twój efekt powinien aktualizować stan. Czy zmieniło się coś, co wpływa na to jak pow
```suggestion
Jeśli rzeczywiście synchronizujesz się z jakimś zewnętrznym systemem, zastanów się, dlaczego i pod jakim warunkiem twój efekt powinien aktualizować stan. Czy zmieniło się coś, co wpływa na to, jak powinien wyglądać twój komponent? Jeśli musisz śledzić jakieś dane, które nie są używane do renderowania, może bardziej odpowiednie będzie użycie [referencji](/reference/react/useRef#referencing-a-value-with-a-ref) (która nie powoduje przerenderowania). Upewnij się, że twój efekt nie aktualizuje stanu (i nie powoduje ponownych renderowań) częściej niż to konieczne.
```

2023-10-07 12:03 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +### Moja funkcja czyszcząca jest uruchamiana nawet, gdy mój komponent nie jest odmontowywany {/*my-cleanup-logic-runs-even-though-my-component-didnt-unmount*/}
```suggestion
### Moja funkcja czyszcząca jest uruchamiana nawet wtedy, gdy mój komponent nie jest odmontowywany {/*my-cleanup-logic-runs-even-though-my-component-didnt-unmount*/}
```

2023-10-07 12:03 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Funkcja czyszcząca uruchamia się nie tylko podczas odmontowywania, ale również przed każdym przerenderowaniem ze zmienionymi zależnościami. Dodatkowo, w trybie deweloperskim, React [uruchamia funkcję
```suggestion
Funkcja czyszcząca uruchamia się nie tylko podczas odmontowywania, ale również przed każdym przerenderowaniem ze zmienionymi zależnościami. Dodatkowo, w trybie deweloperskim, React [uruchamia funkcję konfigurującą oraz czyszczącą dodatkowy raz, tuż po zamontowaniu komponentu.](#my-effect-runs-twice-when-the-component-mounts)
```

2023-10-07 12:03 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Jeśli masz kod czyszczący bez odpowiadającego mu kodu konfigurującego, zazwyczaj oznacza to, że kod ten może powodować problemy:
```suggestion
Jeśli masz kod czyszczący bez odpowiadającego mu kodu konfigurującego, zazwyczaj to on jest przyczyną problemów:
```

2023-10-07 12:03 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +  // 🔴 Unikaj: Logika czyszczenia bez odpowiadającej jej logiki konfiguracyjnej.
```suggestion
  // 🔴 Unikaj: Logika czyszczenia bez odpowiadającej jej logiki konfigurującej.
```

2023-10-07 12:03 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Twoja logika czyszcząca powinna być "symetryczna" względem logiki konfiguracyjnej i powinna zatrzymać lub cofać to, co zrobiła funkcja konfiguracyjna:
```suggestion
Twoja logika czyszcząca powinna być "symetryczna" względem logiki konfigurującej i powinna zatrzymać lub wycofać to, co zrobiła funkcja konfigurująca:
```

2023-10-07 12:03 UTC, jakubdrozdek commented on src/content/reference/react/useEffect.md
> +Jeśli Twój efekt musi wstrzymać przeglądarkę przed [pokazaniem zawartości na ekranie,](/learn/render-and-commit#epilogue-browser-paint) zastąp `useEffect` z pomocą [`useLayoutEffect`](/reference/reac
```suggestion
Jeśli twój efekt musi wstrzymać przeglądarkę przed [pokazaniem zawartości na ekranie,](/learn/render-and-commit#epilogue-browser-paint) zamień `useEffect` na [`useLayoutEffect`](/reference/react/useLayoutEffect). Pamiętaj, że **nie jest to konieczne w przypadku zdecydowanej większości efektów.** Będziesz tego potrzebować tylko wtedy, gdy konieczne jest uruchomienie efektu przed tym, jak przeglądarka zacznie wyświetlać zawartość, na przykład do pomiaru i pozycjonowania dymka podpowiedzi, zanim użytkownik go zobaczy.
```

2023-10-07 19:04 UTC, dawidowski commented
> @dawidowski Wiem, że naskrobałem wiele komentarzy, ale większość z nich odnosi się do tych samych, powtarzanych błędów. Ogólnie to brawo, całość czytało się przyjemnie i płynnie :) Trzymasz się użytego wcześniej słownictwa, piszesz składnie i zrozumiale. 🎉 👏🏻

Spokojnie, nie musisz się tłumaczyć 😄
Nie mam problemu z liczbą komentarzy. Staram się być dokładnym i otwartym na nawet najmniejsze sugestie, więc nie krępuj się 😉

2023-10-08 18:49 UTC, jakubdrozdek approved these changes

2023-10-08 18:49 UTC, merged